PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE IF NOT EXISTS "d1_migrations"(
		id         INTEGER PRIMARY KEY AUTOINCREMENT,
		name       TEXT UNIQUE,
		applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
INSERT INTO "d1_migrations" ("id","name","applied_at") VALUES(1,'0001_initial_schema.sql','2026-06-25 16:17:44');
INSERT INTO "d1_migrations" ("id","name","applied_at") VALUES(2,'0002_seed_data.sql','2026-06-25 16:17:44');
INSERT INTO "d1_migrations" ("id","name","applied_at") VALUES(3,'0002_add_artists.sql','2026-06-26 18:03:34');
INSERT INTO "d1_migrations" ("id","name","applied_at") VALUES(4,'0003_add_address.sql','2026-06-27 07:01:08');
INSERT INTO "d1_migrations" ("id","name","applied_at") VALUES(5,'0004_add_pincode.sql','2026-06-27 08:29:53');
INSERT INTO "d1_migrations" ("id","name","applied_at") VALUES(6,'0005_booking_modes.sql','2026-06-27 10:14:20');
INSERT INTO "d1_migrations" ("id","name","applied_at") VALUES(7,'0006_booking_logic_fields.sql','2026-06-27 10:34:11');
INSERT INTO "d1_migrations" ("id","name","applied_at") VALUES(8,'0007_add_specific_slots.sql','2026-06-27 18:00:19');
CREATE TABLE services (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  name            TEXT NOT NULL,
  slug            TEXT UNIQUE NOT NULL,
  description     TEXT,
  duration_min    INTEGER NOT NULL,
  price_from      INTEGER,
  price_to        INTEGER,
  is_active       INTEGER DEFAULT 1,
  display_order   INTEGER DEFAULT 0
, booking_mode TEXT DEFAULT 'time_slot');
INSERT INTO "services" ("id","name","slug","description","duration_min","price_from","price_to","is_active","display_order","booking_mode") VALUES(5,'Bridal','bridal','Exclusive bridal mehendi design',60,NULL,NULL,1,1,'time_slot');
INSERT INTO "services" ("id","name","slug","description","duration_min","price_from","price_to","is_active","display_order","booking_mode") VALUES(6,'Destination Wedding','destination_wedding','Mehendi artist travel to venue',60,NULL,NULL,1,2,'time_slot');
INSERT INTO "services" ("id","name","slug","description","duration_min","price_from","price_to","is_active","display_order","booking_mode") VALUES(7,'Wedding Mehendi Function','wedding_function','Mehendi for family and guests',60,NULL,NULL,1,3,'time_slot');
INSERT INTO "services" ("id","name","slug","description","duration_min","price_from","price_to","is_active","display_order","booking_mode") VALUES(8,'Pre-Wedding','pre_wedding','Engagement, haldi, and sangeet ceremonies',60,NULL,NULL,1,4,'time_slot');
INSERT INTO "services" ("id","name","slug","description","duration_min","price_from","price_to","is_active","display_order","booking_mode") VALUES(9,'Festival','festival','Traditional festival celebrations',60,NULL,NULL,1,5,'time_slot');
INSERT INTO "services" ("id","name","slug","description","duration_min","price_from","price_to","is_active","display_order","booking_mode") VALUES(10,'Birthdays and Gatherings','birthday_party','Birthday, kitty party, and baby shower gatherings',60,NULL,NULL,1,6,'time_slot');
INSERT INTO "services" ("id","name","slug","description","duration_min","price_from","price_to","is_active","display_order","booking_mode") VALUES(11,'Corporate Event','corporate_event','Brand activations and office events',60,NULL,NULL,1,7,'time_slot');
INSERT INTO "services" ("id","name","slug","description","duration_min","price_from","price_to","is_active","display_order","booking_mode") VALUES(12,'Casual and Personal','casual','Personal mehendi sessions',60,NULL,NULL,1,8,'time_slot');
CREATE TABLE availability_rules (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  day_of_week     INTEGER NOT NULL,
  start_time      TEXT NOT NULL,
  end_time        TEXT NOT NULL,
  slot_gap_min    INTEGER DEFAULT 30,
  is_active       INTEGER DEFAULT 1
, specific_slots TEXT);
INSERT INTO "availability_rules" ("id","day_of_week","start_time","end_time","slot_gap_min","is_active","specific_slots") VALUES(1,1,'08:00','19:00',30,1,NULL);
INSERT INTO "availability_rules" ("id","day_of_week","start_time","end_time","slot_gap_min","is_active","specific_slots") VALUES(2,2,'08:00','19:00',30,1,NULL);
INSERT INTO "availability_rules" ("id","day_of_week","start_time","end_time","slot_gap_min","is_active","specific_slots") VALUES(3,3,'08:00','19:00',30,1,NULL);
INSERT INTO "availability_rules" ("id","day_of_week","start_time","end_time","slot_gap_min","is_active","specific_slots") VALUES(4,4,'08:00','19:00',30,1,NULL);
INSERT INTO "availability_rules" ("id","day_of_week","start_time","end_time","slot_gap_min","is_active","specific_slots") VALUES(5,5,'08:00','19:00',30,1,NULL);
INSERT INTO "availability_rules" ("id","day_of_week","start_time","end_time","slot_gap_min","is_active","specific_slots") VALUES(6,6,'08:00','19:00',30,1,NULL);
CREATE TABLE blocked_slots (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  blocked_date    TEXT NOT NULL,
  start_time      TEXT,
  end_time        TEXT,
  reason          TEXT,
  created_at      TEXT DEFAULT (datetime('now'))
);
INSERT INTO "blocked_slots" ("id","blocked_date","start_time","end_time","reason","created_at") VALUES(2,'2026-06-30',NULL,NULL,'hh','2026-06-25 18:53:57');
CREATE TABLE admin_sessions (
  token       TEXT PRIMARY KEY,
  created_at  TEXT DEFAULT (datetime('now')),
  expires_at  TEXT NOT NULL
);
CREATE TABLE gallery_images (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  r2_key          TEXT NOT NULL,
  alt_text        TEXT,
  style_tag       TEXT,
  occasion_tag    TEXT,
  is_visible      INTEGER DEFAULT 1,
  display_order   INTEGER DEFAULT 0,
  created_at      TEXT DEFAULT (datetime('now'))
);
CREATE TABLE testimonials (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  customer_name   TEXT NOT NULL,
  occasion        TEXT,
  city            TEXT,
  year            INTEGER,
  quote           TEXT NOT NULL,
  photo_r2_key    TEXT,
  is_visible      INTEGER DEFAULT 1,
  display_order   INTEGER DEFAULT 0
);
INSERT INTO "testimonials" ("id","customer_name","occasion","city","year","quote","photo_r2_key","is_visible","display_order") VALUES(1,'Priya Sharma','Wedding','Delhi',2024,'The detail in my bridal mehndi was breathtaking. Every guest asked who the artist was. She understood exactly what I wanted before I could even explain it.',NULL,1,1);
INSERT INTO "testimonials" ("id","customer_name","occasion","city","year","quote","photo_r2_key","is_visible","display_order") VALUES(2,'Ananya Gupta','Engagement','Jaipur',2024,'I was nervous about my engagement mehndi but she made the whole experience so calming. The design was elegant and the colour came out so dark — exactly what I hoped for.',NULL,1,2);
INSERT INTO "testimonials" ("id","customer_name","occasion","city","year","quote","photo_r2_key","is_visible","display_order") VALUES(3,'Meera Patel','Wedding','Lucknow',2023,'She travelled to Lucknow for my wedding and was worth every penny. My mehndi lasted over three weeks and I still look at the photos. Truly an artist.',NULL,1,3);
INSERT INTO "testimonials" ("id","customer_name","occasion","city","year","quote","photo_r2_key","is_visible","display_order") VALUES(4,'sanket','bridal','pune',2026,'loved it :love',NULL,1,0);
CREATE TABLE artists (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    bio TEXT,
    photo_r2_key TEXT,
    is_active INTEGER DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "artists" ("id","name","bio","photo_r2_key","is_active","created_at") VALUES(1,'Aakriti','Founder and Lead Artist',NULL,1,'2026-06-26 18:03:34');
INSERT INTO "artists" ("id","name","bio","photo_r2_key","is_active","created_at") VALUES(2,'yoo','fff',NULL,1,'2026-06-26 18:46:47');
CREATE TABLE IF NOT EXISTS "bookings" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  booking_ref TEXT UNIQUE NOT NULL,
  
  
  service_id INTEGER NULL,
  
  
  appointment_date TEXT NOT NULL,
  appointment_time TEXT,
  
  
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_whatsapp TEXT,
  customer_email TEXT,
  customer_city TEXT,
  customer_pincode TEXT,
  customer_address TEXT,
  
  
  event_type TEXT,
  event_date TEXT,
  notes TEXT,
  
  
  occasion_type TEXT,
  is_bridal INTEGER DEFAULT 0,
  bridal_scope TEXT,
  family_headcount INTEGER DEFAULT 0,
  family_design_style TEXT,
  headcount_range TEXT,
  headcount_numeric INTEGER,
  design_style TEXT,
  body_coverage TEXT,
  addons TEXT,
  booking_urgency TEXT,
  location_type TEXT,
  venue_address TEXT,
  travel_charge INTEGER DEFAULT 0,
  estimated_duration_mins INTEGER,
  recommended_package TEXT,
  estimated_price_min INTEGER,
  estimated_price_max INTEGER,
  is_multiday INTEGER DEFAULT 0,
  reference_image_urls TEXT,
  admin_notes TEXT,
  final_confirmed_price INTEGER,
  
  status TEXT DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
, status_updated_at TEXT, decline_reason TEXT, assigned_artist_id INTEGER REFERENCES artists(id));
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(1,'AKT-20260706-8646',1,'2026-07-06','11:30','Jane Doe','+919876543210',NULL,'jane@example.com','Delhi',NULL,NULL,NULL,'confirmed','yes',NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'pending',400001,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(2,'AKT-20260626-8491',4,'2026-06-26','15:20','Sanket Patil','+918767436317',NULL,'patilsanket9823@gmail.com','Pune',NULL,'2026-06-19',NULL,'confirmed',NULL,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'pending',400001,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(3,'AKT-20260626-4487',1,'2026-06-26','11:30','Sanket Patil','+918767436317',NULL,'patilsanket9823@gmail.com','BENGALURU','Teej','2026-06-19',NULL,'confirmed',NULL,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'pending',400001,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(4,'AKT-20260627-3692',1,'2026-06-27','15:00','Sanket Patil','+918767436317','+918767436317','patilsanket9823@gmail.com','BENGALURU','Diwali','2026-06-10',NULL,'declined',NULL,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'sorry i am already booked',400001,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(5,'AKT-20260627-7659',1,'2026-06-27','08:00','sanket Patil','+918767436317','+918767436317','patilsanket9823@gmail.com','Pimpri-Chinchwad','Diwali','2026-06-18',NULL,'confirmed','',NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'pending',400001,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(6,'AKT-20260627-4015',4,'2026-06-27','14:40','sanket Patil','+918767436317','+918767436317','patilsanket9823@gmail.com','Pimpri-Chinchwad','Teej','2026-06-27',NULL,'confirmed',NULL,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'pending',400001,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(7,'AKT-20260627-5308',3,'2026-06-27','15:30','Sanket Patil','+918767436317','+918767436317','patilsanket9823@gmail.com','BENGALURU','Eid','2026-06-16',NULL,'confirmed','',NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'pending',400001,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(8,'AKT-20260708-1166',2,'2026-07-08','10:30','sanket Patil','+918767436317','+918767436317','patilsanket9823@gmail.com','Pimpri-Chinchwad','Karwa Chauth','2026-07-02',NULL,'confirmed',NULL,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'pending',400001,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(9,'AKT-20260627-7748',4,'2026-06-27','18:00','sanket patil','+910876743631','+910876743631','patilsanket9823@gmail.com','Kolhapur','Karwa Chauth',NULL,'hhh','confirmed',NULL,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'pending',400001,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(10,'AKT-20260627-7052',2,'2026-06-27','11:45','Sanket Patil','+910876743631',NULL,'patilsanket9823@gmail.com','Pune','Karwa Chauth',NULL,NULL,'confirmed',NULL,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'pending',400001,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(11,'AKT-20260627-4848',2,'2026-06-27','13:00','Sanket Patil','+910876743631',NULL,'patilsanket9823@gmail.com','Delhi',NULL,NULL,NULL,'confirmed',NULL,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'pending',400001,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(12,'AKT-20260629-9868',3,'2026-06-29','10:30','Sanket Namdev Patil','+918767436317','+918767436317','patilsanket9823@gmail.com','Chennai',NULL,NULL,'jj','confirmed','',NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'pending',400001,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(13,'AKT-20260629-7705',1,'2026-06-29','15:00','sanket Patil','+910876743631',NULL,'patilsanket9823@gmail.com','Pune',NULL,NULL,NULL,'pending',NULL,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'pending',400001,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(14,'AKT-20260629-6201',4,'2026-06-29','08:40','sanket Patil','+910876743631','+910876743631','patilsanket9823@gmail.com','Chennai',NULL,NULL,NULL,'pending',NULL,NULL,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'pending',411018,NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(15,'AKT-20260629-1633',NULL,'2026-06-29','08:00','sanket Patil','8767436317',NULL,'patilsanket9823@gmail.com',NULL,NULL,NULL,NULL,NULL,replace('403,E wing,5th floor\nJai Ganesh vardhast society, kharalwadi','\n',char(10)),'bridal',1,'hands_elbow',10,'simple','2_5',NULL,'intricate','["hands_elbow","feet"]','["reference_design"]','1_3_days','studio',NULL,0,525,'extended_day',6435,8223,0,'[]',NULL,NULL,'pending','2026-06-27 11:01:18',NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(16,'AKT-20260629-1055',NULL,'2026-06-29','17:00','sanket Patil','8767436317',NULL,'patilsanket9823@gmail.com',NULL,NULL,NULL,NULL,NULL,replace('403,E wing,5th floor\nJai Ganesh vardhast society, kharalwadi','\n',char(10)),'bridal',1,'hands_wrist',0,NULL,NULL,NULL,'simple','["hands_wrist"]','[]','7_days_plus','studio',NULL,0,90,'quick_session',1080,1380,0,'[]',NULL,NULL,'pending','2026-06-27 11:12:09',NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(17,'AKT-20260702-6418',NULL,'2026-07-02','08:00','sanket Patil','8767436317',NULL,'patilsanket9823@gmail.com',NULL,NULL,NULL,NULL,NULL,replace('403,E wing,5th floor\nJai Ganesh vardhast society, kharalwadi','\n',char(10)),'bridal',1,'hands_elbow',0,NULL,NULL,NULL,'intricate','["feet"]','["stone_tikki"]','7_days_plus','studio',NULL,0,120,'quick_session',2070,2645,0,'[]',NULL,NULL,'completed','2026-06-27 12:04:44','2026-06-27 17:10:19',NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(18,'AKT-20260708-7174',NULL,'2026-07-08','08:00','sanket patil','8767436317',NULL,'patilsanket9823@gmail.com',NULL,NULL,NULL,NULL,NULL,replace('Vadakashivale\nKarveer','\n',char(10)),'wedding_function',0,X'',0,NULL,'31_50',NULL,'simple','["hands_and_feet"]','["colored_mehndi"]','7_days_plus','studio',NULL,0,1600,'multiday',33660,43010,1,'[]',NULL,NULL,'pending','2026-06-27 16:02:40',NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(19,'AKT-20260710-6787',NULL,'2026-07-10','08:00','Sanket Patil','8767436317',NULL,'patilsanket9823@gmail.com',NULL,NULL,NULL,NULL,NULL,'FF21-PODS,Thubarahalli,Whitefield','destination_wedding',0,'',0,NULL,'16_30',NULL,'intricate','["hands_and_feet"]','["colored_mehndi"]','7_days_plus','studio',NULL,0,4697,'multiday',52965,67678,1,'[]',NULL,NULL,'pending','2026-06-27 16:07:14',NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(20,'AKT-20260716-3490',NULL,'2026-07-16','12:08','sanket Patil','8767436317',NULL,'patilsanket9823@gmail.com',NULL,NULL,NULL,NULL,NULL,replace('403,E wing,5th floor\nJai Ganesh vardhast society, kharalwadi','\n',char(10)),'festival',0,'',0,NULL,'2_5',NULL,'arabic','["hands_wrist","hands_elbow"]','["reference_design"]','7_days_plus','studio',NULL,0,248,'half_day',2106,2691,0,'[]',NULL,NULL,'pending','2026-06-27 16:09:03',NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(21,'AKT-20260703-5721',NULL,'2026-07-03','08:00','sanket Patil','8767436317',NULL,'patilsanket9823@gmail.com',NULL,NULL,NULL,NULL,NULL,replace('403,E wing,5th floor\nJai Ganesh vardhast society, kharalwadi','\n',char(10)),'destination_wedding',0,'',0,NULL,'2_5',NULL,'simple','["hands_wrist"]','["glitter"]','3_7_days','studio',NULL,0,105,'quick_session',1350,1725,0,'[]',NULL,NULL,'pending','2026-06-27 16:12:41',NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(22,'AKT-20260704-6451',NULL,'2026-07-04','08:00','sanket Patil','8767436317',NULL,'patilsanket9823@gmail.com',NULL,NULL,NULL,NULL,NULL,NULL,'destination_wedding',0,'',0,NULL,'1',NULL,'arabic','["hands_wrist"]','["reference_design"]','3_7_days','studio',NULL,0,82,'quick_session',540,690,0,'[]',NULL,NULL,'declined','2026-06-27 16:42:45','2026-06-27 17:05:16','yo',NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(23,'AKT-20260703-1196',NULL,'2026-07-03','11:00','sanket Patil','8767436317',NULL,'patilsanket9823@gmail.com',NULL,NULL,NULL,NULL,NULL,NULL,'bridal',1,'hands_elbow, hands_wrist',0,NULL,NULL,NULL,'intricate','["hands_elbow"]','["glitter"]','3_7_days','studio',NULL,0,195,'half_day',3060,3910,0,'[]','',NULL,'cancelled','2026-06-27 16:44:27','2026-06-27 17:10:28',NULL,2);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(24,'AKT-20260709-8705',NULL,'2026-07-09','11:00','sanket Patil','8767436317','8767436317','patilsanket9823@gmail.com','Pimpri-Chinchwad','411018',NULL,NULL,NULL,NULL,'destination_wedding',0,'',0,NULL,'1',NULL,'simple','["hands_wrist"]','["reference_design"]','7_days_plus','home_venue',replace('403,E wing,5th floor\nJai Ganesh vardhast society, kharalwadi','\n',char(10)),0,55,'quick_session',270,345,0,'[]','',NULL,'completed','2026-06-27 16:54:18','2026-06-27 17:50:04',NULL,1);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(25,'AKT-20260702-3254',NULL,'2026-07-02','10:00','sanket Patil','8767436317',NULL,'patilsanket9823@gmail.com',NULL,NULL,NULL,NULL,NULL,NULL,'bridal',1,'hands_wrist',0,NULL,NULL,NULL,NULL,'["hands_wrist"]','["reference_design"]','3_7_days','studio',NULL,0,90,'quick_session',1080,1380,0,'[]','',NULL,'cancelled','2026-06-27 17:50:33','2026-06-27 17:52:12',NULL,2);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(26,'AKT-20260703-4255',NULL,'2026-07-03','10:00','sanket Patil','8767436317',NULL,'patilsanket9823@gmail.com',NULL,NULL,NULL,NULL,NULL,NULL,'wedding_function',0,NULL,0,NULL,'1',NULL,'arabic','["hands_wrist"]','["stone_tikki"]','3_7_days','studio',NULL,0,82,'quick_session',810,1035,0,'[]',NULL,NULL,'pending','2026-06-27 18:07:09',NULL,NULL,NULL);
INSERT INTO "bookings" ("id","booking_ref","service_id","appointment_date","appointment_time","customer_name","customer_phone","customer_whatsapp","customer_email","customer_city","customer_pincode","customer_address","event_type","event_date","notes","occasion_type","is_bridal","bridal_scope","family_headcount","family_design_style","headcount_range","headcount_numeric","design_style","body_coverage","addons","booking_urgency","location_type","venue_address","travel_charge","estimated_duration_mins","recommended_package","estimated_price_min","estimated_price_max","is_multiday","reference_image_urls","admin_notes","final_confirmed_price","status","created_at","status_updated_at","decline_reason","assigned_artist_id") VALUES(27,'AKT-20260702-1387',6,'2026-07-02','09:00','Sanket Namdev Patil','8767436317','8767436317','patilsanket9823@gmail.com',NULL,NULL,NULL,NULL,NULL,NULL,'destination_wedding',0,NULL,0,NULL,'2_5',NULL,'arabic','["hands_wrist"]','["reference_design"]','3_7_days','studio',NULL,0,201,'half_day',1620,2070,0,'[]','',NULL,'confirmed','2026-06-28 07:18:29','2026-06-28 07:40:08',NULL,1);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('d1_migrations',8);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('services',12);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('availability_rules',6);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('testimonials',4);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('blocked_slots',2);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('gallery_images',1);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('artists',2);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('bookings',27);
CREATE INDEX idx_blocked_slots_date ON blocked_slots(blocked_date);